<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Analytics\Form\AnalyticsByDownloadForm|\Analytics\Form\AnalyticsByResourceForm $form
 * @var \Analytics\Api\Representation\StatRepresentation[] $resources
 * @var \Analytics\Api\Representation\StatRepresentation[] $stats
 * @var string $userStatus
 * @var string $type
 * @var array $columns
 */

include __DIR__ . '/../../site/analytics/by-stat.phtml';
